
defaults:
  - override hydra_logging: colorlog
  - override job_logging: colorlog

run: 
  dir: ${paths.log_dir}/${experiment_name}/runs
sweep:
  dir: ${paths.log_dir}/${experiment_name}/multiruns/
  subdir: ${hydra.job.num}