defaults:
  - classifier.yaml
  - _self_

strategy:
  _target_: fccgan.models.strategies.classifier_strategies.CDANStrategy
  discriminator:
    _target_: fccgan.base.networks.misc.DiscriminatorDANN
    input_nc: 1024
    ndf: 2048 
    norm: 'batch'
    sigmoid: true
  cdan_loss:
    _target_: fccgan.base.torch.losses.ConditionalDomainAdversarialLoss
    entropy_conditioning: true
    randomized: true
    num_classes: ${model.strategy.classifier.num_classes}
    features_dim: 768
    randomized_dim: ${model.strategy.discriminator.input_nc}
      


