_target_: sda_dls.models.model.Classifier
strategy:
  _target_: sda_dls.models.strategies.classifier_strategies.TwoDomainClassifierStrategy
  classifier:
    _target_: sda_dls.base.networks.classifiers.ConvNext
    network: 'convnext_tiny'
    num_classes: 281
    load_imagenet: True
  label_smoothing: 0.1
  weight_init:
    _target_: torch.nn.init.normal_
    _partial_: true
  stages_to_freeze: 1
  val_metrics:
    _target_: torchmetrics.MetricCollection
    prefix: 'val_'
    metrics:
      - _target_: torchmetrics.classification.MulticlassF1Score
        num_classes: ${model.strategy.classifier.num_classes}
        average: 'none'
  test_metrics:
    _target_: torchmetrics.MetricCollection
    prefix: 'test_'
    metrics:
      - _target_: torchmetrics.classification.MulticlassF1Score
        num_classes: ${model.strategy.classifier.num_classes}
        average: 'none'
  nc_src: 21
optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 1e-2
  betas: [0.9, 0.999]
  eps: 1e-08
  weight_decay: 0.01
  amsgrad: False
scheduler:
  _target_: torch.optim.lr_scheduler.CosineAnnealingLR
  _partial_: True
  T_max: ${trainer.max_epochs}
compile: True