defaults:
  - dual_head
  - _self_

strategy:
  _target_: fccgan.models.strategies.two_head_strategies.EntropicDualHeadStrategy
  generator:
    _target_: fccgan.base.networks.generators.ResnetGenerator
    input_nc: 3
    output_nc: 3
    ngf: 64
    use_dropout: true
    norm: instance
    n_blocks: 9
    padding_type: reflect
  transforms:
    _target_: torchvision.transforms.Compose
    transforms:
      - _target_: torchvision.transforms.v2.Normalize
        mean: [-1, -1, -1]
        std: [2, 2, 2]
      - _target_: torchvision.transforms.v2.Resize
        size: 224
      - _target_: torchvision.transforms.v2.RandomHorizontalFlip
      - _target_: torchvision.transforms.v2.RandAugment
      - _target_: torchvision.transforms.v2.RandomErasing
      - _target_: torchvision.transforms.v2.Normalize
        mean: [0.5, 0.5, 0.5]
        std: [0.5, 0.5, 0.5]
  pretrained_path_G:
    - ${paths.log_dir}/cyclegan_resnet/runs/checkpoints/best.ckpt
    - "gen_A"
  lambda_eos: ???
