_target_: fccgan.models.inpainting.InpaintingModel
generator:
  _target_: fccgan.base.networks.generators.ViTUNetGenerator
  features: 384
  n_heads: 6
  n_blocks: 6
  ffn_features: 1536
  embed_features: 384
  activ: 'gelu'
  norm: 'layer'
  unet_features_list: [48, 96, 192, 384]
  unet_activ: 'leakyrelu'
  unet_norm: 'instance'
  unet_downsample: 'conv'
  unet_upsample: 'upsample-conv'
  rezero: True
  activ_output: 'tanh'
  image_shape: [3, 256, 256]
masking_module:
  _target_: fccgan.base.torch.image_masking.ImagePatchRandomMasking
  patch_size: [32, 32]
  fraction: 0.4
weight_init:
  _target_: torch.nn.init.normal_
  _partial_: true
  mean: 0.0
  std: 0.02
optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 1.25e-3
  betas:
  - 0.9
  - 0.999
  eps: 1.0e-08
  weight_decay: 0.05
  amsgrad: false
scheduler:
  _target_: torch.optim.lr_scheduler.CosineAnnealingLR
  _partial_: true
  T_max: ${trainer.max_epochs}
compile: True
