data:
  _target_: fccgan.data.data_loader.BaseDataModule
  train_set:
    _target_: fccgan.data.image_folder.UnpairedImageFolder
    root_A: ${paths.data_dir}/source/train
    root_B: ${paths.data_dir}/target_partial_split/train
    labels_path: ${paths.data_dir}/labels.json
    transform_list:
    - _target_: torchvision.transforms.Resize
      size:
      - 246
      - 246
    - _target_: torchvision.transforms.RandomCrop
      size:
      - 224
      - 224
    - _target_: torchvision.transforms.RandAugment
      num_ops: 3
      magnitude: 9
    - _target_: torchvision.transforms.ToTensor
    - _target_: torchvision.transforms.Normalize
      mean:
      - 0.5
      - 0.5
      - 0.5
      std:
      - 0.5
      - 0.5
      - 0.5
  batch_size_train: 16
  num_workers_train: 4
  val_set:
    _target_: fccgan.data.image_folder.SingleDomainImageFolder
    root: ${paths.data_dir}/target_full/val
    labels_path: ${paths.data_dir}/labels.json
    transform_list:
    - _target_: torchvision.transforms.Resize
      size:
      - 224
      - 224
    - _target_: torchvision.transforms.ToTensor
    - _target_: torchvision.transforms.Normalize
      mean:
      - 0.5
      - 0.5
      - 0.5
      std:
      - 0.5
      - 0.5
      - 0.5
  batch_size_val: 128
  num_workers_val: 4
  test_set:
    _target_: fccgan.data.image_folder.SingleDomainImageFolder
    root: ${paths.data_dir}/target_full/test
    labels_path: ${paths.data_dir}/labels.json
    transform_list:
    - _target_: torchvision.transforms.Resize
      size:
      - 224
      - 224
    - _target_: torchvision.transforms.ToTensor
    - _target_: torchvision.transforms.Normalize
      mean:
      - 0.5
      - 0.5
      - 0.5
      std:
      - 0.5
      - 0.5
      - 0.5
  batch_size_test: 128
  num_workers_test: 4
model:
  _target_: fccgan.models.model.Classifier
  strategy:
    _target_: fccgan.models.strategies.classifier_strategies.DANNStrategy
    classifier:
      _target_: fccgan.base.networks.classifiers.ConvNext
      network: convnext_tiny
      num_classes: 156
      load_imagenet: true
    label_smoothing: 0.1
    weight_init:
      _target_: torch.nn.init.normal_
      _partial_: true
    stages_to_freeze: 2
    val_metrics:
      _target_: torchmetrics.MetricCollection
      prefix: val_
      metrics:
      - _target_: torchmetrics.classification.MulticlassF1Score
        num_classes: ${model.strategy.classifier.num_classes}
        average: none
    test_metrics:
      _target_: torchmetrics.MetricCollection
      prefix: test_
      metrics:
      - _target_: torchmetrics.classification.MulticlassF1Score
        num_classes: ${model.strategy.classifier.num_classes}
        average: none
    nc_src: 21
    best_metric_key: val_MulticlassF1Score_source
    maximize_best_metric: true
    discriminator:
      _target_: fccgan.base.networks.misc.DiscriminatorDANN
      input_nc: 768
      ndf: 1024
  optimizer:
    _target_: torch.optim.AdamW
    _partial_: true
    lr: 0.0002
    betas:
    - 0.9
    - 0.999
    eps: 1.0e-08
    weight_decay: 0.1
    amsgrad: false
  scheduler:
    _target_: torch.optim.lr_scheduler.CosineAnnealingLR
    _partial_: true
    T_max: ${trainer.max_epochs}
    eta_min: 0.0
    last_epoch: -1
    verbose: true
  compile: true
trainer:
  _target_: lightning.pytorch.trainer.Trainer
  default_root_dir: ${paths.output_dir}
  max_epochs: 60
  accelerator: gpu
  devices:
  - 1
  log_every_n_steps: 20
  check_val_every_n_epoch: 4
  deterministic: false
callbacks:
  model_checkpoint:
    _target_: lightning.pytorch.callbacks.ModelCheckpoint
    dirpath: ${paths.output_dir}/checkpoints
    filename: '{epoch}-{val_MulticlassF1Score_source: .3f}'
    monitor: val_MulticlassF1Score_source
    verbose: false
    save_last: null
    save_top_k: 1
    mode: max
    auto_insert_metric_name: true
    save_weights_only: false
    every_n_train_steps: null
    train_time_interval: null
    every_n_epochs: ${trainer.check_val_every_n_epoch}
    save_on_train_epoch_end: null
  model_summary:
    _target_: lightning.pytorch.callbacks.RichModelSummary
    max_depth: 1
  rich_progress_bar:
    _target_: lightning.pytorch.callbacks.RichProgressBar
logger:
  wandb:
    _target_: lightning.pytorch.loggers.wandb.WandbLogger
    name: ${experiment_name}
    save_dir: ${paths.output_dir}
    offline: false
    id: null
    anonymous: null
    project: FCCGAN
    log_model: false
    prefix: ''
    group: ''
    tags: []
    job_type: ''
paths:
  root_dir: .
  data_dir: ${paths.root_dir}/datasets/ccsv2ssb
  log_dir: ${paths.root_dir}/logs/
  output_dir: ${hydra:runtime.output_dir}
  work_dir: ${hydra:runtime.cwd}
extras:
  ignore_warnings: false
  enforce_tages: true
  print_config: true
experiment_name: dann
train: true
