defaults:
  - data: unpaired.yaml
  - model: supcon_resnet.yaml
  - trainer: default.yaml
  - callbacks: generative.yaml
  - logger: wandb.yaml
  - paths: default.yaml
  - extras: default.yaml
  - hydra: default.yaml
  - _self_

experiment_name: ???
train: True

