defaults:
  - data: supcon.yaml
  - model: supcon.yaml
  - trainer: default.yaml
  - callbacks: default.yaml
  - logger: wandb.yaml
  - paths: default.yaml
  - extras: default.yaml
  - hydra: default.yaml
  - _self_

trainer:
  max_epochs: 120
  devices: 0
  check_val_every_n_epochs: 5

train: True
experiment_name: supcon