defaults:
  - data: target_full.yaml
  - model: classifier.yaml
  - trainer: default.yaml
  - callbacks: default.yaml
  - logger: wandb.yaml
  - paths: default.yaml
  - extras: default.yaml
  - hydra: default.yaml
  - _self_

trainer:
  max_epochs: 60
  devices: 0
  check_val_every_n_epochs: 5

data:
  train_set:
    root: '${paths.data_dir}/target/train'
  val_set:
    root: '${paths.data_dir}/target/val'

experiment_name: 'two_step_backbone'

train: True